### ISSUE TITLE
Crash when changing Plugin-specific parameters with SRCF Plugin enable

### ISSUE THREAD

**Issue by NerdyNinja11** [jsyiek/AU2#25]
As title

**Comment by NerdyNinja11** [comment]
Enable SRCFPlugin
Log in
Select Plugin-config -> Plugin-specific parameters

Traceback (most recent call last):
  File "C:\Users\P320\AppData\Local\Programs\Python\Python39\Scripts\au2-script.py", line 33, in <module>
    sys.exit(load_entry_point('Auto-Umpire-2', 'console_scripts', 'au2')())
  File "c:\users\p320\documents\assassins\au2\au2\AU2\frontends\inquirer_cli.py", line 526, in main
    qs.append(inquirer.List(name=i, choices=["*EXIT*"] + f(), ignore=lambda x: any(a[j] == "*EXIT*" for j in range(i))))
  File "c:\users\p320\documents\assassins\au2\au2\AU2\plugins\CorePlugin.py", line 436, in gather_config_names
    for c in p.config_exports:
AttributeError: 'SRCFPlugin' object has no attribute 'config_exports'

**Comment by jsyiek** [comment]
Right ok, this just needs the line `self.config_exports = []` in `SRCFPlugin.py`. I can do this later today when I get home.
